# Generated by Django 6.0 on 2026-01-06 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Atención')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de Consulta')),
                ('sintomas', models.TextField(verbose_name='Sintomatología')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico Médico')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento Indicado')),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='gestion.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
