# Generated by Django 6.0 on 2026-01-20 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_consulta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='presion_arterial',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='sintomas',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='consulta',
            name='fur',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Última Regla'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='glicemia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consulta',
            name='peso_madre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='programa',
            field=models.CharField(choices=[('GENERAL', 'Consulta General'), ('RESPIRATORIO', 'Programa Respiratorio'), ('ENDOCRINO', 'Endocrinometabólico'), ('RUTA_MATERNA', 'Ruta Materna'), ('SSR', 'Salud Sexual y Reproductiva')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tension_arterial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(default='GENERAL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='GENERAL', max_length=20),
            preserve_default=False,
        ),
    ]
