# Generated by Django 6.0.5 on 2026-05-16 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('asic', models.CharField(max_length=100, verbose_name='ASIC')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCDI',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol_profesional', models.CharField(choices=[('Médico', 'Médico'), ('Enfermero', 'Enfermero'), ('Administrativo', 'Administrativo'), ('Mantenimiento', 'Mantenimiento'), ('Obrero', 'Obrero')], max_length=50)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Permiso', 'Permiso'), ('Retirado', 'Retirado')], default='Activo', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal del CDI',
            },
        ),
        migrations.CreateModel(
            name='InventarioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bien_nacional', models.CharField(max_length=50, unique=True)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('tipo_equipo', models.CharField(choices=[('Médico', 'Médico'), ('Electrónico', 'Electrónico'), ('Mobiliario', 'Mobiliario')], max_length=50)),
                ('ubicacion_especifica', models.CharField(max_length=100)),
                ('estado_fisico', models.CharField(choices=[('Operativo', 'Operativo'), ('Dañado', 'Dañado'), ('En Reparación', 'En Reparación')], default='Operativo', max_length=20)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cdi.personalcdi')),
            ],
            options={
                'verbose_name_plural': 'Inventario de Equipos',
            },
        ),
        migrations.CreateModel(
            name='ControlEndocrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(auto_now_add=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_cm', models.IntegerField()),
                ('imc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='HbA1c')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cdi.paciente')),
                ('atendido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cdi.personalcdi')),
            ],
            options={
                'verbose_name_plural': 'Controles Endocrinos',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(auto_now_add=True)),
                ('primera_sucesiva', models.CharField(choices=[('Primera', 'Primera'), ('Sucesiva', 'Sucesiva')], max_length=20)),
                ('metodo_entregado', models.CharField(max_length=100)),
                ('preservativo_masculino', models.IntegerField(default=0)),
                ('atendido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cdi.personalcdi')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cdi.paciente')),
            ],
            options={
                'verbose_name_plural': 'Planificación Familiar',
            },
        ),
        migrations.CreateModel(
            name='RutaMaterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_control', models.DateField(auto_now_add=True)),
                ('semanas_embarazo', models.IntegerField()),
                ('eje', models.CharField(max_length=100)),
                ('direccion_detallada', models.TextField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cdi.personalcdi')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cdi.paciente')),
            ],
            options={
                'verbose_name_plural': 'Ruta Materna',
            },
        ),
    ]
