# Generated by Django 6.0.5 on 2026-05-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_cedula',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='personalcdi',
            name='tipo_cedula',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1),
        ),
    ]
