# Generated by Django 6.0.5 on 2026-05-19 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cdi', '0002_paciente_tipo_cedula_personalcdi_tipo_cedula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlendocrino',
            options={},
        ),
        migrations.RenameField(
            model_name='controlendocrino',
            old_name='atendido_por',
            new_name='medico_tratante',
        ),
        migrations.RemoveField(
            model_name='controlendocrino',
            name='hba1c',
        ),
        migrations.RemoveField(
            model_name='controlendocrino',
            name='imc',
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, help_text='LPM', null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, help_text='RPM', null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='glucemia_ayunas',
            field=models.IntegerField(blank=True, help_text='mg/dL', null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='gestion_cdi.paciente'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='talla_cm',
            field=models.IntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='tension_arterial',
            field=models.CharField(blank=True, help_text='Ej: 120/80', max_length=10, null=True),
        ),
    ]
