# Generated by Django 6.0.5 on 2026-05-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cdi', '0003_alter_controlendocrino_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacionfamiliar',
            options={},
        ),
        migrations.RemoveField(
            model_name='planificacionfamiliar',
            name='atendido_por',
        ),
        migrations.AddField(
            model_name='planificacionfamiliar',
            name='antecedente_obstetrico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planificacionfamiliar',
            name='diu',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='planificacionfamiliar',
            name='establecimiento_salud',
            field=models.CharField(default='CDI El Llanito', max_length=100),
        ),
        migrations.AddField(
            model_name='planificacionfamiliar',
            name='implante',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='planificacionfamiliar',
            name='municipio',
            field=models.CharField(default='Sucre', max_length=100),
        ),
        migrations.AddField(
            model_name='planificacionfamiliar',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planificacionfamiliar',
            name='semana',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semana Epidemiológica'),
        ),
        migrations.AddField(
            model_name='rutamaterna',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planificacionfamiliar',
            name='metodo_entregado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planificacionfamiliar',
            name='primera_sucesiva',
            field=models.CharField(default='Primera', max_length=20),
        ),
    ]
