# Generated by Django 6.0.5 on 2026-05-24 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cdi', '0004_alter_planificacionfamiliar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacionfamiliar',
            options={'verbose_name_plural': 'Planificación Familiar'},
        ),
        migrations.RemoveField(
            model_name='controlendocrino',
            name='medico_tratante',
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='asociacion_cv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='colesterol_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='conducta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='creatinina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='diabetes_mellitus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='dislipidemia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='enf_tiroidea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='enfermedad_renal_cronica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='hba1c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='insulina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='medicamentos_entregados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='obesidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='observaciones_finales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='otras_patologias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='pas',
            field=models.CharField(choices=[('Primera', 'Primera'), ('Sucesiva', 'Sucesiva')], default='Primera', max_length=10),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='pie_diabetico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='sede_tratamiento',
            field=models.CharField(default='CDI El Llanito', max_length=150),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='sobre_peso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='tgo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='tgp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='trigliceridos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlendocrino',
            name='urea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='glucemia_ayunas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cdi.paciente'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='talla_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='tension_arterial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
