# Generated by Django 6.0.5 on 2026-05-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cdi', '0005_alter_planificacionfamiliar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlendocrino',
            name='pas',
            field=models.CharField(choices=[('Primera', 'Primera'), ('Sucesiva', 'Sucesiva')], default='Primera', max_length=10, verbose_name='P.A.S.'),
        ),
    ]
