# Generated by Django 6.0.5 on 2026-06-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cdi', '0006_alter_controlendocrino_pas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlendocrino',
            name='asociacion_cv',
            field=models.BooleanField(default=False, verbose_name='Asociación C.V.'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='diabetes_mellitus',
            field=models.BooleanField(default=False, verbose_name='Diabetes Mellitus'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='dislipidemia',
            field=models.BooleanField(default=False, verbose_name='Dislipidemia'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='enf_tiroidea',
            field=models.BooleanField(default=False, verbose_name='Enf. Tiroidea'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='enfermedad_renal_cronica',
            field=models.BooleanField(default=False, verbose_name='Enfermedad Renal Crónica'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='insulina',
            field=models.BooleanField(default=False, verbose_name='Insulina'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='obesidad',
            field=models.BooleanField(default=False, verbose_name='Obesidad'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='pie_diabetico',
            field=models.BooleanField(default=False, verbose_name='Pie Diabético'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='sede_tratamiento',
            field=models.CharField(default='CDI El Llanito', max_length=150, verbose_name='Sede de Tratamiento'),
        ),
        migrations.AlterField(
            model_name='controlendocrino',
            name='sobre_peso',
            field=models.BooleanField(default=False, verbose_name='Sobre Peso'),
        ),
    ]
